# Birds CUB dataset
birds_images_path: "dataset/birds/CUB_200_2011//CUB_200_2011/images/"
birds_embedding_path: "dataset/birds/cub_icml/"
birds_text_path: "dataset/birds/cvpr2016_cub/text_c10/"
birds_dataset_path: "dataset/birds/birds.hdf5"
val_split_path: "dataset/birds/cub_icml/valclasses.txt"
train_split_path: "dataset/birds/cub_icml/trainclasses.txt"
test_split_path: "dataset/birds/cub_icml/testclasses.txt"


# flowers dataset
flowers_images_path: "dataset/flowers/"
flowers_embedding_path: "dataset/flowers/flowers_icml/"
flowers_text_path: "dataset/flowers/cvpr2016_flowers/text_c10/"
flowers_dataset_path: "dataset/flowers/flowers.hdf5"

flowers_val_split_path: "dataset/flowers/flowers_icml/valclasses.txt"
flowers_train_split_path: "dataset/flowers/flowers_icml/trainclasses.txt"
flowers_test_split_path: "dataset/flowers/flowers_icml/testclasses.txt"